spring:
  application:
    name: catalog-service
  data:
    mongodb:
      host: mongodb-catalog
      port: 27017
      database: catalog_service_db
      authentication-database: admin
      username: rootuser
      password: rootpass
      auto-index-creation: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/