#spring:
#  application:
#    name: catalog-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/catalog_service_db
#    username: root
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
spring:
  application:
    name: catalog-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalog_service_db

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/